language: node_js
sudo: true
node_js:
  - 'node'
os:
  - linux
  - osx
script:
  - chmod +x ./tools/install/julia.sh
  - chmod +x ./tools/ci/travis.sh
  - ./tools/install/julia.sh
  - ./tools/ci/travis.sh

