# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: node_js

# Is `sudo` required? If not, jobs are run on container-based infrastructure.
sudo: true

node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
  - '3'
  - '2'
  - '1'
  - '0.12'
  - '0.10'

before_install:
  # Update the npm client. Older clients cannot, e.g., handle scoped modules.
  - npm update -g npm

script:
  - ./tools/install/julia.sh

